spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/usertesting?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
#  security:
#    user:
#      name: "admin"
#      password: "admin"