spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/usertesting?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  mail:
    host : smtp.gmail.com
    port : 587
    username : ${MAIL_USERNAME}
    password : ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true